[package]
name = "lazy_static"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
publish = false

[lib]
proc-macro = true

[dependencies]
syn = { path = "../../../", features = ["full"] }
quote = "0.4"
proc-macro2 = { version = "0.2", features = ["nightly"] }
