[package]
name = "unstable"
version = "0.1.0"
authors = ["Sergio Benitez <sb@sergio.bz>"]
publish = false

[lib]
proc-macro = true

[dependencies]
syn = { path = "../../", features = ["full"] }
proc-macro2 = { version = "0.4", features = ["nightly"] }
